name: Contextos
on: push
jobs:
  check_aprendiendo_github_actions:
    if: ${{ github.ref == 'refs/heads/aprender-github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python propuesta.py