name: Trigger Workflow
run-name: Triggers_Workflow
on:
  push:
    branches:
      - aprender-github-actions
  pull_request:
    types: [opened]
    branches:
      - aprender-github-actions
    paths:
      - 'scripts/**'
  schedule:
    - cron: '30 00 * * *'  # Runs at 00:30 UTC every day
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python holamundo.py