name: Triggers
run-name: Triggers Workflow
on:
  push:
    branches:
      - aprender-github-actions
  pull_request:
    types: [synchronize]
    paths:
      - '**.py'
  schedule:
    - cron: '00 23 * * *'
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script holamundo
        run: python holamundo.py
      - name: Correr script propuesta
        run: python propuesta.py
